### ISSUE TITLE
Make null=False the default.

### ISSUE THREAD

**Issue by mrmachine** [shrubberysoft/django-picklefield#1]
Making null=True the default just because isnull lookups are possible violates the principle of least surprise. All other Django fields are null=False by default even though isnull lookups are possible, although not very useful if no objects can have Python None value for the field in question. If the user wants to allow this Python None values (which is when isnull lookups become useful) they can specify null=True.

**Comment by gintas** [comment]
Hi,
I'm sorry I somehow missed this issue (spam filter?), but hey, better later than never. I will investigate tomorrow.

**Comment by gintas** [comment]
Fixed in ba1f726c1fbda40731f0e4a2b63761ff164655bb . Thanks.
