### ISSUE TITLE
Don't pickle objects that don't need to be pickled.

### ISSUE THREAD

**Issue by mrmachine** [shrubberysoft/django-picklefield#2]
By checking of the assigned value is str or unicode and not pickling those in get_db_prep_value(), more lookups can be used with PickledObjectField, e.g. contains, icontains, endswith, iendswith, iexact, regex, iregex, search, startswith, istartswith. Obviously these lookups will only return results for objects which are not pickled, but that's OK because it doesn't make sense to do those lookups for values other than str and unicode.

**Comment by gintas** [comment]
I think that if you want to use string lookup methods, then you should use a text field. This field is meant specifically for more complicated data structures, and I don't think it makes much sense to special-case strings.

**Comment by mrmachine** [comment]
I use pickle fields a lot, for example to allow users to create new forms via an admin interface (thus avoiding having to change forms and views python code and restart the server) by choosing a data type for a Question object and storing the answer in a pickle field on an Answer object. A lot of the time the answers are string, and it's often useful to use string lookups to find specific answers, but there are also usually a couple of non-string Question objects on the same form (boolean, date, time). It doesn't make sense to store answers in a different field if they are string, as this makes accessing answers more difficult -- you need to know which data type each question is to access its answer. It also doesn't make sense to needlessly pickle those string values which makes it impossible to use string lookups. What's lost by allowing data that is already string or unicode to remain un-pickled? What's gained by forcing it to be pickled?

**Comment by mrmachine** [comment]
Also, the great benefit of pickle fields in my mind is that it allows people to store unknown types of data (at the time of model declaration). In that case you don't always know if string might be stored in a pickle field, but if it is, string lookups are certainly useful in mining that data.

**Comment by gintas** [comment]
I understand the benefits of being able to search through strings, but I am reluctant to make such a change because I don't see a fully backwards-compatible and foolproof way to detect whether a value in the database is actually a literal string or a pickled objects.

You seem to have a specific usecase; feel free to just copy django-picklefield into your project and change the implementation as you see fit (or even better, subclass and extend).

**Comment by mrmachine** [comment]
I don't see how there is any backwards compatible issue. Any existing pickled field data will simply not be returned in a queryset that uses string lookups. If the a developer is using string lookups on a pickle field they should know that pickled records aren't going to be returned. If a developer wants to convert existing data from pickled to string format, all they need to do is loop through all records, check if the unpickled data is string or unicode, and if it is re-save the object which would then (by whatever mechanism is implemented) save it as raw data without pickling.

I actually developed my own PickleField which works this way long before I stumbled across this project, so I don't need to maintain a local branch of django-picklefield. But I do find my PickleField very useful in that it can be used to store data when the type will vary, not only when the type is known but there is simply no native type. The above use case is only one of several instances when a pickle field has been used to store string and other data types, for which string lookups are useful.

**Comment by gintas** [comment]
One obvious problem is how to discern between a pickled object and a string that happens to contain content that looks like a pickle representation.

**Comment by mrmachine** [comment]
That seems highly improbable, and even then would only happen when performing basic string lookups such as `contains` with simple strings (like a single letter or number, or random string e.g. from a random unique code). I don't think that could be considered a backwards compatible issue, since string lookups are not even possible with pickle fields now.

If anyone actually finds this a problem, it could easily be solved with a small comment in the documentation explaining that when performing simple string lookups there is a very small chance that the subtring they are searching for might appear in some pickled data, and in cases where that seems possible (when the developer is searching for string data that resembles picked data), the developer should take care to check the results or use more explicit filters. E.g. check the type of the unpickled objects when looping through results or use more explicit field lookups in `filter` and `exclude` calls.
