### ISSUE TITLE
Corrupted PickledObjectField value

### ISSUE THREAD

**Issue by sachinrekhi** [shrubberysoft/django-picklefield#3]
I found an issue that is causing data corruption in the PickledObjectField!

I have a model that has a PickledObjectField, which works fine. But then I run a QuerySet operation in which I defer() the PickledObjectField, then make a few edits to the model, and then perform a model.save().

But now when I attempt to read the PickledObjectField value in all future QuerySet operations, I get returned the raw base64 pickled string instead of a python object! It seems like the data has been corrupted somehow. But sometimes I can manually call dbsafe_decode to get back the python object, but I shouldn't have to do that. But even using dbsafe_decode only works sometimes.

When I looked into the SQL queries being executed on the model.save(), it runs a SELECT to get the value of the pickledobjectfield from the db first so that it has the full model which is then saved. It appears that the full pickled object field string is appropriately saved, but for some reason it still isn't working.

Any help would be great!

**Comment by gintas** [comment]
Hi,
sorry to get back to you so late - I somehow missed this report. It's difficult to deduce the problem from your description. Are you able to reproduce the problem, or perhaps you have a database dump with the broken data?

**Comment by sachinrekhi** [comment]
So it turns out the issue wasn't specific to PickledObjectField, but a larger issue across Django. I reported the issue and it has now been fixed for release with Django 1.2. You can see the details here:

http://code.djangoproject.com/ticket/12734

**Comment by gintas** [comment]
Thanks!
