### ISSUE TITLE
Add South 0.7 support

### ISSUE THREAD

**Issue by adamn** [shrubberysoft/django-picklefield#4]
http://south.aeracode.org/docs/tutorial/part4.html#simple-inheritance

This simple-inheritance method probably needs to be added to PickleField in order to make it work with South 0.7

**Comment by gintas** [comment]
Hello, Adam,
thanks for letting me know. I'll try to address this during the weekend.

**Comment by gintas** [comment]
South support added in 1ea1bf9293bccb52b77bd838706e97d053a8e1a9 . Please have a look and confirm.

**Comment by adamn** [comment]
Looks good to me.
