### ISSUE TITLE
Empty or null field writes 8 bytes of data in table

### ISSUE THREAD

**Issue by test157** [shrubberysoft/django-picklefield#5]
if field is not set, so it's empty string (not null) - after saving in database it will has this value gAJVAC4=

it's better to save in database just empty string in this case, just to save database space. 

with null seems to me it's also better to save its value directly.

**Comment by gintas** [comment]
I think None should be stored as NULL at the moment. As for strings, I don't think there's much to gain by adding a special case for empty strings here, especially since the difference between empty unicode strings and empty byte strings would be lost (or we'd just have to special-case one).
