### ISSUE TITLE
DeprecationWarning for methods 'get_db_prep_lookup', 'get_db_prep_value' (Django 1.2.3)

### ISSUE THREAD

**Issue by zimnyx** [shrubberysoft/django-picklefield#6]
DeprecationWarning: A Field class whose get_db_prep_lookup method hasn't been updated to take `connection` and `prepared` arguments.

**Comment by gintas** [comment]
Fixed in version 0.1.7. Thanks for reporting this!

**Comment by zimnyx** [comment]
There are still DeprecationWarning generated by picklefield code. Takie a look, all this methods need to be updated:

```
    for attr in ('db_type', 'get_db_prep_save'):
        setattr(new_cls, attr, call_with_connection(getattr(new_cls, attr)))
    for attr in ('get_db_prep_lookup', 'get_db_prep_value'):
        setattr(new_cls, attr, call_with_connection_and_prepared(getattr(new_cls, attr)))
```

**Comment by gintas** [comment]
I fixed another place, please try the latest version and let me know if the warnings are finally gone.

**Comment by zimnyx** [comment]
Warnings gone away :-)
Thanks!

**Comment by tymofij** [comment]
In Django trunk one is still present, saying

<pre>
lib/python/django/db/models/fields/subclassing.py:80: DeprecationWarning: A Field class whose get_db_prep_value method hasn't been updated to take `connection` and `prepared` arguments.
  new_class = super(SubfieldBase, cls).__new__(cls, base, name, attrs)
</pre>

**Comment by tymofij** [comment]
<pre>
diff --git a/src/picklefield/fields.py b/src/picklefield/fields.py
index 0e2de16..3bc78bf 100644
--- a/src/picklefield/fields.py
+++ b/src/picklefield/fields.py
@@ -108,7 +108,7 @@ class PickledObjectField(models.Field):
                     raise
         return value
 
-    def get_db_prep_value(self, value):
+    def get_db_prep_value(self, value, connection=None, prepared=False):
         """
         Pickle and b64encode the object, optionally compressing it.

</pre>

does the trick for 1.3 and 1.2

**Comment by gintas** [comment]
tymofij, that fix is already included in 0.1.9. Are you sure you're not using an older version?

**Comment by tymofij** [comment]
I am using trunk, see https://github.com/shrubberysoft/django-picklefield/blob/master/src/picklefield/fields.py

**Comment by tymofij** [comment]
Ok, I see. You just did not push gintas/django-picklefield here.

**Comment by gintas** [comment]
Yeah. Shrubbery Software is a long dead entity and I'm trying to disassociate my projects from it.
