### ISSUE TITLE
Is it really necessary to deepcopy every time object is pickled?

### ISSUE THREAD

**Issue by bradleyayers** [shrubberysoft/django-picklefield#8]
https://github.com/shrubberysoft/django-picklefield/blob/master/src/picklefield/fields.py#L31-37

Sorry if I seem naive but could you clarify why deepcopy is necessary every time an object is pickled? It seems unecessary. I read the comment for it but am confused by the term "lookup value".

**Comment by gintas** [comment]
See testLookups in tests.py. I have to admit I do not deeply understand the reason why cPickle sometimes produces different values. The reason why you want a canonical serialized form is that you may want to search by object, i.e. objects.get(foo_field__exact=value). Having different serialization forms for the same value would make such lookups unreliable.
